# Generated by Django 3.1.7 on 2022-02-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=30)),
                ('production_year', models.CharField(max_length=50)),
                ('available_seat', models.IntegerField()),
                ('desc', models.TextField()),
                ('vehicle_color', models.CharField(max_length=30)),
                ('license_plate', models.IntegerField()),
            ],
        ),
    ]
